[package]
name = "croco_lang"
version = "0.4.1"
authors = ["truelossless <esteban.gressard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.6.0"
dyn-clonable = "0.9.0"
gumdrop = "0.8.0" # lighter alternative to clap
ureq = { version = "*", default-features = false, features = ["native-tls"] } # lighter alternative to reqwest
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm10-0" }

[features]
default = ["crocoi", "crocol"]
crocoi = [] # the croco interpreter backend
crocol = [] # the croco llvm backend 

[lib]
name = "croco"
path = "src/lib.rs"

[[bin]]
name = "crocoi"
path = "src/crocoi/cli.rs"

[[bin]]
name = "crocol"
path = "src/crocol/cli.rs"

[profile.release]
panic = "abort"
lto = true
debug = 0