[package]
name = "croco_lang"
version = "0.2.0"
authors = ["truelossless <esteban.gressard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.3.0"
dyn-clone = "1.0.1"
gumdrop = "0.8.0" # lighter alternative to clap
reqwest = { version = "0.10.4", features = ["blocking"] }

[lib]
name = "croco"
path = "src/lib.rs"

[[bin]]
name = "croco"
path = "src/croco.rs"

[profile.release]
panic = "abort"
lto = true
debug = 0