[package]
name = "croco_lang"
version = "0.1.0"
authors = ["truelossless <esteban.gressard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.3.0"
dyn-clone = "1.0.1"

[lib]
name = "crocolib"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/test.rs"