name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  # build croco on every OS
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build release
      run: cargo build --release --target-dir ${{ matrix.os }}
  
  # upload the resulting binaries to github releases
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:

      # get the commit hash
      # https://github.community/t/add-short-sha-to-github-context/16418/11
      - name: get commit infos
        id: commit
        run: |
          echo "::set-output name=hash::$(echo ${GITHUB_SHA} | cut -c1-8)"
          echo "::set-output name=msg::$(git log --format=%B -n 1 ${{ github.event.after }})"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit.outputs.hash }}
          release_name: Release ${{ steps.commit.outputs.hash }}
          body: This is an automated build from commit ${{ steps.commit.outputs.hash }}.\n\n${{ steps.commit.outputs.msg }}
          draft: false
          prerelease: true
      
      - name: upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest/release/croco
          asset_name: croco-linux-${{ steps.commit.outputs.hash }}
          asset_content_type: application/x-elf

      - name: upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-latest/release/croco.exe
          asset_name: croco-windows-${{ steps.commit.outputs.hash }}.exe
          asset_content_type: application/x-msdownload
      
      - name: upload MacOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-latest/release/croco
          asset_name: croco-macos-${{ steps.commit.outputs.hash }}
          asset_content_type: application/x-elf